# Generated by Django 5.0.6 on 2024-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_description',
            field=models.TextField(default='Default Value', max_length=250),
            preserve_default=False,
        ),
    ]
