# Generated by Django 5.0.6 on 2024-05-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_imgage',
            new_name='doc_image',
        ),
    ]
